// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUgKV5oSdLztr_AmnBRfRUxFS52U5H5VI',
    appId: '1:488334136345:web:52e1fc955a425fd0444688',
    messagingSenderId: '488334136345',
    projectId: 'inspiration-acf13',
    authDomain: 'inspiration-acf13.firebaseapp.com',
    storageBucket: 'inspiration-acf13.appspot.com',
    measurementId: 'G-Y2EKLNS401',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVYpy2h30bGD9T8ZK0J5ZsREVUEle3_Dc',
    appId: '1:488334136345:android:aea4434a985a6f9d444688',
    messagingSenderId: '488334136345',
    projectId: 'inspiration-acf13',
    storageBucket: 'inspiration-acf13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1cc3SCreQJ5nT9VJULp8HSysNo06zjOQ',
    appId: '1:488334136345:ios:df510d5aa411373b444688',
    messagingSenderId: '488334136345',
    projectId: 'inspiration-acf13',
    storageBucket: 'inspiration-acf13.appspot.com',
    iosBundleId: 'com.example.inspirationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1cc3SCreQJ5nT9VJULp8HSysNo06zjOQ',
    appId: '1:488334136345:ios:df510d5aa411373b444688',
    messagingSenderId: '488334136345',
    projectId: 'inspiration-acf13',
    storageBucket: 'inspiration-acf13.appspot.com',
    iosBundleId: 'com.example.inspirationapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUgKV5oSdLztr_AmnBRfRUxFS52U5H5VI',
    appId: '1:488334136345:web:ce6ad536a997fa54444688',
    messagingSenderId: '488334136345',
    projectId: 'inspiration-acf13',
    authDomain: 'inspiration-acf13.firebaseapp.com',
    storageBucket: 'inspiration-acf13.appspot.com',
    measurementId: 'G-FGPRCQPD8R',
  );
}
